### ISSUE TITLE
Can't run NaverLogin.login

### ISSUE THREAD

**Issue by teemobk** [dooboolab/react-native-naver-login#1]
Hi @dooboolab ,
When i run my app, in onNaverLogin function:
If i use name: kConsumerKey, kConsumerSecret, kServiceAppName, kServiceAppUrlScheme
```ruby
const initials = {
      kConsumerKey: 'VN6WKGFQ3pJ0xBXRtlN9',
      kConsumerSecret: 'AHBgzH9ZkM',
      kServiceAppName: 'dooboolab',
      kServiceAppUrlScheme: 'dooboolaburlscheme', // only for iOS
};
```
then app crash: **Unfortunately, app has stopped**
If i use name: key, secret, name, urlScheme
```ruby
const initials = {
	key: 'VN6WKGFQ3pJ0xBXRtlN9',
	secret: 'AHBgzH9ZkM',
	name: 'dooboolab',
	urlScheme: 'dooboolaburlscheme', // only for iOS
};
```
then run to "console.log(props);" then **stop**:
```ruby
const naverLogin = (props) => {
  return new Promise(function (resolve, reject) {
      console.log(props);
      NaverLogin.login(props, (err, token) => {
        console.log(`\n\n  Token is fetched  :: ${token} \n\n`);
        ...
      });
  });
};
```
This is my config:
```ruby
"dependencies": {
    "apsl-react-native-button": "^3.1.0",
    "react": "16.0.0-beta.5",
    "react-native": "0.49.3",
    "react-native-extended-stylesheet": "^0.7.0",
    "react-native-naver-login": "^1.0.6",
    "react-navigation": "^1.0.0-beta.13"
  }
```
Can you help me? Thanks

**Comment by dooboolab** [comment]
@teemobk 
Can you tell me which OS did you face error?

**Comment by JJMoon** [comment]
There was a bug in iOS bridge methods. Sorry for that.

The constants example of Readme file was wrong.  kConsumerKey ...  are right.
Please refer to the newest Readme. Sorry for that too. 

Please upgrade to newest version.

**Comment by teemobk** [comment]
Thanks @dooboolab and @JJMoon ,
I run on Android. About error: **Unfortunately, app has stopped**, i add to /android/app/src/main/AndroidManifest.xml:
```
<activity
        android:name="com.nhn.android.naverlogin.ui.OAuthLoginActivity"
        android:screenOrientation="portrait"
        android:theme="@android:style/Theme.Translucent.NoTitleBar" />
<activity
        android:name="com.nhn.android.naverlogin.ui.OAuthLoginInAppBrowserActivity"
        android:label="OAuth2.0 In-app"
        android:screenOrientation="portrait" />
```
Fixed!
Great, Thank you very much^^

**Comment by dooboolab** [comment]
@teemobk 
OMG.. Sorry man.
![image](https://user-images.githubusercontent.com/27461460/31480444-d5939e16-af58-11e7-8dbc-2fc521ff5a74.png)

Your error looks like the error in the package name because I have set the default pacakage name.

I will update this library to npm 1.0.8 fixing the problem.

![image](https://user-images.githubusercontent.com/27461460/31480478-ff04bd02-af58-11e7-9edb-e406dd7dd556.png)

Then you will have to define applicationId in app/build.gradle file.

**Comment by teemobk** [comment]
Thank you very much!^^
