### ISSUE TITLE
Cannot read packageName

### ISSUE THREAD

**Issue by kcoms** [dooboolab/react-native-naver-login#2]
react-native-naver-login 1.0.13 Error

Error:Cannot read packageName from /...path.../node_modules/react-native-naver-login/android/src/main/AndroidManifest.xml

아래와 같이 변경하면 에러가 사라집니다.

manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="${applicationId}"
=>
manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.dooboolab.naverlogin"

**Comment by dooboolab** [comment]
@kcoms 
한국분이신 것 같네요.
네 아마 example code를 실행시켰을 때 저런 문제점이 있으셨을 겁니다.
라이브러리로 사용했을 시 관련 문제점이 생기면 다시 알려주세요.

감사합니다.

**Comment by kcoms** [comment]
@dooboolab 
라이브러리로 사용했을때 나온 에러입니다.
react-native-naver-login 의 AndroidManifest.xml 에서 사용할 applicationId가 정의되지 않아서
나온 에러인듯 싶네요.
현재 노드 모듈 추가할때마다 저부분을 계속 수정해야.. ^^;;;
확인하시고 수정해주시면 감사하겠습니다.

**Comment by dooboolab** [comment]
@kcoms 
네 리포트 감사합니다.
확인해보니 $(applicationId)로 되면 오류가 발생하는 것이 맞네요.
수정해서 올려드리겠습니다.
