### ISSUE TITLE
안드로이드에서 빌드시 packageName 을 찾을 수 없다고 오류가 납니다. 

### ISSUE THREAD

**Issue by nopedev** [dooboolab/react-native-naver-login#3]
모듈 만들어주셔서 매우 감사합니다.

안드로이드에서 빌드시 ```/node_modules/react-native-naver-login/android/src/main/AndroidManifest.xml```  의 ```package="${applicationId}"``` 부분에서 packageName 을 찾을 수 없다고 오류가 납니다. 

```react-native 0.51.0``` 사용중입니다.

Readme 에 있는것처럼 ```android/app/build.gradle``` 파일에
```
android {
    ...
    defaultConfig {
        ...
        applicationId "com.myapp"
        ...
    }
    ....
}
```
이렇게 설정되어 있는 상태입니다.

```/node_modules/react-native-naver-login/android/src/main/AndroidManifest.xml``` 파일에 강제로
```package="com.dooboolab.naverlogin"```이라고 수정하니까 일단은 빌드도 되고 기능도 정상적으로 작동하는것 같습니다.(제 경우는 activity 를 등록해 주어야 작동하네요.)

그래도 모듈파일을 직접 수정하는 방식은 좀 아닌것 같아서 해결책을 찾아보고 있는데 마땅한 방법을 못찾겠네요.

제 환경에서 ```package="${applicationId}"```의 ```applicationId```값을 못받아오는것 같은데 혹시 조언가능하신 해결책 있을까요.

**Comment by nopedev** [comment]
closed 열어보니까 이미 논의된 내용이군요.
이슈 닫겠습니다.

**Comment by dooboolab** [comment]
@nopedev 
안녕하세요. 제가 이슈를 착각하고 잘못 닫은 것 같습니다.
확인을 해보니 com.dooboolab.naverlogin으로 해줘야 정상 빌드가 될 것 같네요.

그렇게 이용해주시면 됩니다.
npm에 새로 업데이트 해드리겠습니다.

감사합니다.
