### ISSUE TITLE
안드로이드 NaverLogin.logout(); 호출시 null 예외 발생.

### ISSUE THREAD

**Issue by nopedev** [dooboolab/react-native-naver-login#4]
안드로이드에서 NaverLogin.logout(); 호출시 null 예외를 떨구고 앱이 종료되는 현상이 있는것 같습니다.

제 소스상에 네이버 로그인이 되어 있는지와 무관하게 앱에서 로그아웃 시 소셜로그인들의 로그아웃을
일괄 호출하는 루틴이 있는데 거기서 예외가 나는것 같습니다.

일단 ```RNNaverLoginModule.java``` 파일 50라인을 아래와 같이 수정해서 예외를 막아놓기는 했는데
null 예외가 떨어지는게 의도된 것인지 아닌지 까지는 제가 알수가 없어서 null 체크 하는부분을 혹시 소스에 반영가능하신지 문의드려봅니다.

```java
@ReactMethod
  public void logout() {
    if (mOAuthLoginModule != null) {
        mOAuthLoginModule.logout(reactContext);
    }
  }
```
새해복 많이 받으세요~

**Comment by dooboolab** [comment]
@nopedev 
네 반영해드리겠습니다.
다음부터는 fork를 뜨신다음 작업하시고 머지 request를 날려주시면
검토하고 반영해드리겠습니다.

감사합니다.

**Comment by nopedev** [comment]
@dooboolab 
감사합니다!
