### ISSUE TITLE
iOS rootViewController 관련 문제

### ISSUE THREAD

**Issue by yunhoi129** [dooboolab/react-native-naver-login#6]
-(void)oauth20ConnectionDidOpenInAppBrowserForOAuth:(NSURLRequest *)request 

이쪽 function 에서

UIViewController *vc = UIApplication.sharedApplication.delegate.window.rootViewController;
[vc presentViewController:inappAuthBrowser animated:NO completion:nil];

이부분을 아래와같이 수정하시면 될 수도 있습니다. (해당 rootViewController 에서 추가로 띄워진 viewController가 있을경우 while 문으로 찾아감), 성능 이슈는 크지 않겠죠.. -_-

UIViewController *topController = [UIApplication sharedApplication].keyWindow.rootViewController;
        while (topController.presentedViewController) {
            topController = topController.presentedViewController;
        }
[topController presentViewController:inappAuthBrowser animated:YES completion:nil];

**Comment by JJMoon** [comment]
아래 이슈에 대한 답변을 주신 것 같습니다. 답변 감사합니다.
아래 이슈는 작업이 머지되면 닫고, 이 이슈는 지금 닫겠습니다.
리포에 가보니 카카오 작업 하고 계신 것 같네요.. ㅎㅎ 환영합니다.
